"""
LangGraph construction for Medical triage agent that analyzes patient symptoms, test results, and doctor observations to assign a triage tier (1: immediate, 2: within 1 year, 3: beyond 1 year) based on diagnosis severity and risk level.

Auto-generated by AI Agent Builder.
"""

import logging
from pathlib import Path
from dotenv import load_dotenv
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

from state import MedicalTriageAgentThatAnalyzesState
from nodes import input_validation_node, assess_and_assign_tier_node
from routing import route_from_input_validation

# Load .env file
_current_dir = Path(__file__).parent
_env_path = _current_dir / ".env"
if not _env_path.exists():
    _env_path = _current_dir.parent.parent.parent / ".env"
load_dotenv(_env_path)

logger = logging.getLogger(__name__)


def create_graph(thread_id: str = None):
    """
    Create the Medical triage agent graph.

    This is a single-node chain-of-thought (COT) agent with input validation.
    
    Architecture:
    - input_validation: Safety guardrail (validates input before processing)
    - assess_and_assign_tier: Single intelligent node that performs complete triage assessment

    Flow:
    input_validation → assess_and_assign_tier → END
    
    Args:
        thread_id: Optional thread ID for conversation persistence
        
    Returns:
        Compiled LangGraph agent
    """
    logger.info("🏗️ Building Medical triage agent graph...")

    # Create graph
    agent = StateGraph(MedicalTriageAgentThatAnalyzesState)

    # Add nodes
    agent.add_node("input_validation", input_validation_node)
    agent.add_node("assess_and_assign_tier", assess_and_assign_tier_node)

    # Add edges
    agent.add_conditional_edges(
        "input_validation",
        route_from_input_validation
    )
    agent.add_edge("assess_and_assign_tier", END)

    # Set entry point
    agent.set_entry_point("input_validation")

    # Compile with checkpointer if thread_id provided
    if thread_id:
        checkpointer = MemorySaver()
        compiled_graph = agent.compile(checkpointer=checkpointer)
        logger.info("✅ Medical triage agent graph compiled successfully (with checkpointer)")
    else:
        compiled_graph = agent.compile()
        logger.info("✅ Medical triage agent graph compiled successfully (without checkpointer)")

    return compiled_graph


# Create singleton instance (compiled graph)
graph = create_graph()