"""
LangGraph construction for Medical triage agent that analyzes patient symptoms, test results, and doctor observations to assign a triage tier (1: immediate, 2: within 1 year, 3: beyond 1 year) based on diagnosis severity and risk level.

Auto-generated by AI Agent Builder.
"""

import logging
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from pathlib import Path
from dotenv import load_dotenv

from state import MedicalTriageAgentThatAnalyzesState
from nodes import input_validation_node, assess_and_assign_tier_node
from routing import route_from_input_validation

logger = logging.getLogger(__name__)

# Load .env file
_current_dir = Path(__file__).parent
_env_path = _current_dir / ".env"
if not _env_path.exists():
    _env_path = _current_dir.parent.parent.parent / ".env"
load_dotenv(_env_path)


def create_graph(thread_id: str = None):
    """
    Create the Medical triage agent graph.

    Nodes:
    1. input_validation: Safety guardrail - validates input before processing
    2. assess_and_assign_tier: Analyze patient symptoms, test results, and doctor observations to determine triage tier

    Flow:
    input_validation → assess_and_assign_tier → END
    """
    logger.info("🏗️ Building Medical triage agent graph...")

    # Create graph
    agent = StateGraph(MedicalTriageAgentThatAnalyzesState)

    # Add nodes
    agent.add_node("input_validation", input_validation_node)
    agent.add_node("assess_and_assign_tier", assess_and_assign_tier_node)

    # Add edges
    agent.add_conditional_edges("input_validation", route_from_input_validation)
    agent.add_edge("assess_and_assign_tier", END)

    # Set entry point
    agent.set_entry_point("input_validation")

    # Compile with checkpointer if thread_id provided
    if thread_id:
        checkpointer = MemorySaver()
        compiled_graph = agent.compile(checkpointer=checkpointer)
    else:
        compiled_graph = agent.compile()

    logger.info("✅ Medical triage agent graph compiled successfully")

    return compiled_graph


# Create singleton instance (compiled graph)
graph = create_graph()