"""
Routing functions for Medical triage agent that analyzes patient symptoms, test results, and doctor observations to assign a triage tier (1: immediate, 2: within 1 year, 3: beyond 1 year) based on diagnosis severity and risk level.

Auto-generated by AI Agent Builder.
"""

import logging
from typing import Literal

from langgraph.graph import END
from state import MedicalTriageAgentThatAnalyzesState

logger = logging.getLogger(__name__)


def route_from_input_validation(state: MedicalTriageAgentThatAnalyzesState) -> str:
    '''
    Route from input validation node.
    
    If validation passed, proceed to triage assessment.
    If validation failed, end (error message already added to messages).
    '''
    if state.get("validation_passed", False):
        logger.info("✅ Input validation passed, routing to triage assessment")
        return "assess_and_assign_tier"
    else:
        logger.warning("❌ Input validation failed, ending conversation")
        return END


def route_from_assess_and_assign_tier(state: MedicalTriageAgentThatAnalyzesState) -> Literal[END]:
    '''
    Route from triage assessment node.
    
    This is the final node, so always route to END.
    '''
    logger.info("✅ Triage assessment complete, ending conversation")
    return END