"""
Routing functions for Medical triage agent that analyzes patient symptoms, test results, and doctor observations to assign a triage tier (1: immediate, 2: within 1 year, 3: beyond 1 year) based on diagnosis severity and risk level.

Auto-generated by AI Agent Builder.
"""

import logging
from typing import Literal
from langgraph.graph import END
from state import MedicalTriageAgentThatAnalyzesState

logger = logging.getLogger(__name__)


def route_from_input_validation(state: MedicalTriageAgentThatAnalyzesState) -> Literal["assess_and_assign_tier", END]:
    """
    Route from input validation to assessment or end.
    
    Returns:
    - "assess_and_assign_tier" if validation passed
    - END if validation failed
    """
    if state.get("validation_passed", False):
        logger.info("✅ Input validation passed, routing to assessment")
        return "assess_and_assign_tier"
    else:
        logger.info("❌ Input validation failed, routing to END")
        return END