"""
Routing functions for Medical triage agent that analyzes patient symptoms, test results, and doctor observations to assign a triage tier (1: immediate, 2: within 1 year, 3: beyond 1 year) based on diagnosis severity and risk level.

Auto-generated by AI Agent Builder.
"""

import logging
from typing import Literal
from langgraph.graph import END
from state import MedicalTriageAgentThatAnalyzesState

logger = logging.getLogger(__name__)


def route_from_input_validation(state: MedicalTriageAgentThatAnalyzesState) -> Literal["assess_and_assign_tier", END]:
    """
    Route from input_validation node.
    If validation passed, proceed to assess_and_assign_tier.
    Otherwise, end the conversation.
    """
    if state.get("validation_passed", False):
        return "assess_and_assign_tier"
    else:
        return END