"""
State model for Medical triage agent that analyzes patient symptoms, test results, and doctor observations to assign a triage tier (1: immediate, 2: within 1 year, 3: beyond 1 year) based on diagnosis severity and risk level.

Auto-generated by AI Agent Builder.
"""

from typing import TypedDict, Optional, List
from typing_extensions import Annotated
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class MedicalTriageAgentThatAnalyzesState(TypedDict):
    """
    State for medical triage agent.
    
    Fields:
    - messages: Conversation history with add_messages reducer
    - validation_passed: Whether input validation succeeded
    - consecutive_validation_failures: Counter for fail-open rate limiting
    - triage_tier: Assigned tier (1, 2, or 3)
    - reasoning: Explanation for tier assignment
    - recommendation: Clinical recommendation
    """
    messages: Annotated[List[BaseMessage], add_messages]
    validation_passed: Optional[bool]
    consecutive_validation_failures: Optional[int]
    triage_tier: Optional[int]
    reasoning: Optional[str]
    recommendation: Optional[str]