"""
Test suite for Medical triage agent that analyzes patient symptoms, test results, and doctor observations to assign a triage tier (1: immediate, 2: within 1 year, 3: beyond 1 year) based on diagnosis severity and risk level.

Auto-generated by AI Agent Builder.
"""

import pytest
from langchain_core.messages import HumanMessage, AIMessage
from graph import graph


@pytest.mark.asyncio
async def test_happy_path_severe_chest_pain_requiring_immediate_attention():
    """
    Test: Happy path - severe chest pain requiring immediate attention
    
    Key decisions:
    - Recognize life-threatening cardiac emergency
    - Assign Tier 1 based on STEMI presentation
    - Provide clear reasoning with clinical correlation
    
    Success criteria: Correctly assigns Tier 1 with appropriate justification for acute MI
    """
    initial_state = {
        "messages": [
            HumanMessage(content="Patient is a 58-year-old male presenting with severe crushing chest pain radiating to left arm for the past 30 minutes. Sweating profusely, shortness of breath. BP: 160/95, HR: 110. ECG shows ST-segment elevation. Troponin levels elevated at 0.8 ng/mL. Doctor notes possible acute MI.")
        ]
    }
    
    config = {"configurable": {"thread_id": "test_severe_chest_pain"}}
    result = await graph.ainvoke(initial_state, config)
    
    # Verify response exists
    assert "messages" in result
    assert len(result["messages"]) > 1
    
    # Get final AI message
    ai_messages = [msg for msg in result["messages"] if isinstance(msg, AIMessage)]
    assert len(ai_messages) > 0
    
    final_response = ai_messages[-1].content.lower()
    
    # Verify Tier 1 assignment
    assert "tier 1" in final_response or "tier 1" in final_response
    assert "immediate" in final_response
    
    # Verify clinical reasoning
    assert any(keyword in final_response for keyword in ["stemi", "myocardial infarction", "cardiac", "st-segment"])


@pytest.mark.asyncio
async def test_happy_path_mild_condition_requiring_routine_follow_up():
    """
    Test: Happy path - mild condition requiring routine follow-up
    
    Key decisions:
    - Identify non-urgent, chronic musculoskeletal condition
    - Assign Tier 3 for routine management
    - Explain lack of serious pathology
    
    Success criteria: Correctly assigns Tier 3 with reasoning that condition is stable and non-urgent
    """
    initial_state = {
        "messages": [
            HumanMessage(content="Patient is a 32-year-old female with occasional mild knee pain during exercise, no swelling, no redness. Pain started 3 months ago. X-ray shows no fractures or significant abnormalities. ROM is normal. Doctor suspects mild patellofemoral syndrome. Patient able to perform daily activities without limitation.")
        ]
    }
    
    config = {"configurable": {"thread_id": "test_mild_knee_pain"}}
    result = await graph.ainvoke(initial_state, config)
    
    ai_messages = [msg for msg in result["messages"] if isinstance(msg, AIMessage)]
    final_response = ai_messages[-1].content.lower()
    
    # Verify Tier 3 assignment
    assert "tier 3" in final_response
    assert "beyond 1 year" in final_response or "routine" in final_response
    
    # Verify reasoning about benign condition
    assert any(keyword in final_response for keyword in ["mild", "benign", "conservative", "non-urgent"])


@pytest.mark.asyncio
async def test_happy_path_moderate_condition_requiring_timely_intervention():
    """
    Test: Happy path - moderate condition requiring timely intervention
    
    Key decisions:
    - Recognize moderate but significant cardiovascular risk
    - Assign Tier 2 for timely but non-emergent treatment
    - Balance current stability with future risk prevention
    
    Success criteria: Correctly assigns Tier 2 recognizing need for timely intervention without emergency status
    """
    initial_state = {
        "messages": [
            HumanMessage(content="Patient is a 45-year-old male with newly diagnosed hypertension. BP readings consistently 155/98 over past 2 weeks. No end-organ damage detected. Fundoscopic exam normal, creatinine 1.1, no proteinuria. Patient asymptomatic but has family history of stroke. Doctor recommends starting antihypertensive therapy and lifestyle modifications.")
        ]
    }
    
    config = {"configurable": {"thread_id": "test_hypertension"}}
    result = await graph.ainvoke(initial_state, config)
    
    ai_messages = [msg for msg in result["messages"] if isinstance(msg, AIMessage)]
    final_response = ai_messages[-1].content.lower()
    
    # Verify Tier 2 assignment
    assert "tier 2" in final_response
    assert "within 1 year" in final_response or "timely" in final_response
    
    # Verify reasoning about cardiovascular risk
    assert any(keyword in final_response for keyword in ["hypertension", "cardiovascular", "risk", "treatment"])


@pytest.mark.asyncio
async def test_edge_case_vague_symptoms_without_objective_findings():
    """
    Test: Error scenario - vague symptoms without objective findings
    
    Key decisions:
    - Acknowledge insufficient information for confident triage
    - Provide provisional tier with caveats
    - Request additional data for proper assessment
    
    Success criteria: Appropriately identifies data insufficiency while providing provisional guidance and requesting more information
    """
    initial_state = {
        "messages": [
            HumanMessage(content="Patient reports 'not feeling well' for several weeks. Denies specific symptoms when asked. Says everything hurts but can't localize. No fever documented. Patient states 'doctors never help me.' No physical exam findings documented. No test results provided. Doctor notes patient seems frustrated.")
        ]
    }
    
    config = {"configurable": {"thread_id": "test_vague_symptoms"}}
    result = await graph.ainvoke(initial_state, config)
    
    ai_messages = [msg for msg in result["messages"] if isinstance(msg, AIMessage)]
    final_response = ai_messages[-1].content.lower()
    
    # Verify agent acknowledges limitations or provides provisional assessment
    assert any(keyword in final_response for keyword in [
        "tier 3", "provisional", "limited", "insufficient", "additional", "evaluation", "complete"
    ])
    
    # Should still provide some guidance
    assert len(final_response) > 100  # Substantive response