"""
Test suite for Medical triage agent that analyzes patient symptoms, test results, and doctor observations to assign a triage tier (1: immediate, 2: within 1 year, 3: beyond 1 year) based on diagnosis severity and risk level.

Auto-generated by AI Agent Builder.
"""

import pytest
from langchain_core.messages import HumanMessage
from graph import graph


@pytest.mark.asyncio
async def test_happy_path_severe_chest_pain_requiring_immediate_attention():
    """Test: Happy path - severe chest pain requiring immediate attention"""
    config = {"configurable": {"thread_id": "test_severe_chest_pain"}}
    
    user_message = "Patient is a 58-year-old male presenting with severe crushing chest pain radiating to left arm for the past 30 minutes. Sweating profusely, shortness of breath. BP: 160/95, HR: 110. ECG shows ST-segment elevation. Troponin levels elevated at 0.8 ng/mL. Doctor notes possible acute MI."
    
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    
    response = result["messages"][-1].content
    assert "Tier 1" in response or "Immediate" in response
    assert result.get("triage_tier") == 1


@pytest.mark.asyncio
async def test_happy_path_mild_condition_requiring_routine_follow_up():
    """Test: Happy path - mild condition requiring routine follow-up"""
    config = {"configurable": {"thread_id": "test_mild_knee_pain"}}
    
    user_message = "Patient is a 32-year-old female with occasional mild knee pain during exercise, no swelling, no redness. Pain started 3 months ago. X-ray shows no fractures or significant abnormalities. ROM is normal. Doctor suspects mild patellofemoral syndrome. Patient able to perform daily activities without limitation."
    
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    
    response = result["messages"][-1].content
    assert "Tier 3" in response or "Beyond 1 year" in response
    assert result.get("triage_tier") == 3


@pytest.mark.asyncio
async def test_happy_path_moderate_condition_requiring_timely_intervention():
    """Test: Happy path - moderate condition requiring timely intervention"""
    config = {"configurable": {"thread_id": "test_hypertension"}}
    
    user_message = "Patient is a 45-year-old male with newly diagnosed hypertension. BP readings consistently 155/98 over past 2 weeks. No end-organ damage detected. Fundoscopic exam normal, creatinine 1.1, no proteinuria. Patient asymptomatic but has family history of stroke. Doctor recommends starting antihypertensive therapy and lifestyle modifications."
    
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    
    response = result["messages"][-1].content
    assert "Tier 2" in response or "Within 1 year" in response
    assert result.get("triage_tier") == 2


@pytest.mark.asyncio
async def test_happy_path_suspicious_mass_requiring_prompt_evaluation():
    """Test: Happy path - suspicious mass requiring prompt evaluation"""
    config = {"configurable": {"thread_id": "test_breast_mass"}}
    
    user_message = "Patient is a 62-year-old female with painless breast lump discovered 2 weeks ago. Lump is hard, irregular, fixed, approximately 2.5 cm. Mammogram shows suspicious mass with microcalcifications, BI-RADS 5. No distant symptoms. Patient otherwise healthy. Doctor recommends urgent biopsy and oncology referral."
    
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    
    response = result["messages"][-1].content
    assert "Tier 2" in response or "Within 1 year" in response
    assert result.get("triage_tier") == 2


@pytest.mark.asyncio
async def test_happy_path_acute_appendicitis_requiring_urgent_surgery():
    """Test: Happy path - acute appendicitis requiring urgent surgery"""
    config = {"configurable": {"thread_id": "test_appendicitis"}}
    
    user_message = "Patient is a 28-year-old male with 12 hours of progressive right lower quadrant pain, started periumbilical then localized. Fever 38.5°C, nausea, one episode of vomiting. Rebound tenderness and guarding present. WBC 16,000 with left shift. CT scan shows inflamed appendix with surrounding fat stranding, no perforation. Doctor diagnosis: acute appendicitis."
    
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    
    response = result["messages"][-1].content
    assert "Tier 1" in response or "Immediate" in response
    assert result.get("triage_tier") == 1


@pytest.mark.asyncio
async def test_happy_path_seasonal_allergies_with_mild_symptoms():
    """Test: Happy path - seasonal allergies with mild symptoms"""
    config = {"configurable": {"thread_id": "test_allergies"}}
    
    user_message = "Patient is a 25-year-old female with sneezing, clear nasal discharge, itchy eyes for 1 week. Symptoms worse in morning, improves indoors. No fever, no shortness of breath. Lungs clear on auscultation. Patient has history of seasonal allergies. Vital signs normal. Doctor suspects allergic rhinitis."
    
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    
    response = result["messages"][-1].content
    assert "Tier 3" in response or "Beyond 1 year" in response
    assert result.get("triage_tier") == 3


@pytest.mark.asyncio
async def test_edge_case_ambiguous_symptoms_with_conflicting_indicators():
    """Test: Edge case - ambiguous symptoms with conflicting indicators"""
    config = {"configurable": {"thread_id": "test_ambiguous_chest_pain"}}
    
    user_message = "Patient is a 50-year-old male with intermittent chest discomfort for 3 days, described as 'pressure' but also 'sharp'. Pain sometimes related to movement, sometimes not. No radiation. Vital signs normal. ECG shows nonspecific ST-T changes. Troponin normal. Patient anxious, recently lost job. Doctor uncertain if cardiac or musculoskeletal vs anxiety."
    
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    
    response = result["messages"][-1].content
    assert "Tier 2" in response or "Within 1 year" in response
    assert result.get("triage_tier") == 2


@pytest.mark.asyncio
async def test_edge_case_borderline_vital_signs_in_elderly_patient():
    """Test: Edge case - borderline vital signs in elderly patient"""
    config = {"configurable": {"thread_id": "test_elderly_weakness"}}
    
    user_message = "Patient is an 82-year-old female with generalized weakness for 2 days. BP 95/60 (baseline 110/70), HR 92, temp 37.8°C. Mild confusion, oriented to person and place but not time. Labs show sodium 132, creatinine 1.4 (baseline 1.0). No obvious infection source. Patient lives alone, has been eating and drinking poorly. Doctor notes possible dehydration vs early sepsis vs medication effect."
    
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    
    response = result["messages"][-1].content
    assert "Tier 1" in response or "Immediate" in response
    assert result.get("triage_tier") == 1


@pytest.mark.asyncio
async def test_error_scenario_missing_critical_test_results():
    """Test: Error scenario - missing critical test results"""
    config = {"configurable": {"thread_id": "test_missing_imaging"}}
    
    user_message = "Patient is a 55-year-old male with severe abdominal pain for 6 hours, constant, 8/10 intensity. Pain in epigastric region. Patient vomiting. Vital signs: BP 100/65, HR 105, temp 37.2°C. Abdomen rigid with guarding. Doctor suspects perforated viscus but imaging not yet available."
    
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    
    response = result["messages"][-1].content
    assert "Tier 1" in response or "Immediate" in response
    assert result.get("triage_tier") == 1


@pytest.mark.asyncio
async def test_error_scenario_vague_symptoms_without_objective_findings():
    """Test: Error scenario - vague symptoms without objective findings"""
    config = {"configurable": {"thread_id": "test_vague_symptoms"}}
    
    user_message = "Patient reports 'not feeling well' for several weeks. Denies specific symptoms when asked. Says everything hurts but can't localize. No fever documented. Patient states 'doctors never help me.' No physical exam findings documented. No test results provided. Doctor notes patient seems frustrated."
    
    result = await graph.ainvoke(
        {"messages": [HumanMessage(content=user_message)]},
        config=config
    )
    
    response = result["messages"][-1].content
    # Should acknowledge insufficient information
    assert ("insufficient" in response.lower() or 
            "limited" in response.lower() or 
            "cannot confidently" in response.lower() or
            "provisional" in response.lower() or
            "low confidence" in response.lower())
    assert result.get("confidence_level") == "low"