"""
Test suite for Medical triage agent that analyzes patient symptoms, test results, and doctor observations to assign a triage tier (1: immediate, 2: within 1 year, 3: beyond 1 year) based on diagnosis severity and risk level.

Auto-generated by AI Agent Builder.
"""

import pytest
from langchain_core.messages import HumanMessage
from graph import graph


@pytest.mark.asyncio
async def test_happy_path_severe_chest_pain_requiring_immediate_attention():
    """
    Test: Happy path - severe chest pain requiring immediate attention
    """
    state = {
        "messages": [
            HumanMessage(content="Patient is a 58-year-old male presenting with severe crushing chest pain radiating to left arm for the past 30 minutes. Sweating profusely, shortness of breath. BP: 160/95, HR: 110. ECG shows ST-segment elevation. Troponin levels elevated at 0.8 ng/mL. Doctor notes possible acute MI.")
        ]
    }
    
    result = await graph.ainvoke(state)
    
    # Verify response exists
    assert "messages" in result
    assert len(result["messages"]) > 0
    
    # Verify Tier 1 assignment
    response_content = result["messages"][-1].content.lower()
    assert "tier 1" in response_content or "tier 1" in response_content
    assert "immediate" in response_content


@pytest.mark.asyncio
async def test_happy_path_mild_condition_requiring_routine_follow_up():
    """
    Test: Happy path - mild condition requiring routine follow-up
    """
    state = {
        "messages": [
            HumanMessage(content="Patient is a 32-year-old female with occasional mild knee pain during exercise, no swelling, no redness. Pain started 3 months ago. X-ray shows no fractures or significant abnormalities. ROM is normal. Doctor suspects mild patellofemoral syndrome. Patient able to perform daily activities without limitation.")
        ]
    }
    
    result = await graph.ainvoke(state)
    
    # Verify response exists
    assert "messages" in result
    assert len(result["messages"]) > 0
    
    # Verify Tier 3 assignment
    response_content = result["messages"][-1].content.lower()
    assert "tier 3" in response_content
    assert "beyond 1 year" in response_content or "routine" in response_content


@pytest.mark.asyncio
async def test_happy_path_moderate_condition_requiring_timely_intervention():
    """
    Test: Happy path - moderate condition requiring timely intervention
    """
    state = {
        "messages": [
            HumanMessage(content="Patient is a 45-year-old male with newly diagnosed hypertension. BP readings consistently 155/98 over past 2 weeks. No end-organ damage detected. Fundoscopic exam normal, creatinine 1.1, no proteinuria. Patient asymptomatic but has family history of stroke. Doctor recommends starting antihypertensive therapy and lifestyle modifications.")
        ]
    }
    
    result = await graph.ainvoke(state)
    
    # Verify response exists
    assert "messages" in result
    assert len(result["messages"]) > 0
    
    # Verify Tier 2 assignment (NOT Tier 3)
    response_content = result["messages"][-1].content.lower()
    assert "tier 2" in response_content
    assert "within 1 year" in response_content or "urgent" in response_content


@pytest.mark.asyncio
async def test_edge_case_ambiguous_symptoms_with_conflicting_indicators():
    """
    Test: Edge case - ambiguous symptoms with conflicting indicators
    """
    state = {
        "messages": [
            HumanMessage(content="Patient is a 50-year-old male with intermittent chest discomfort for 3 days, described as 'pressure' but also 'sharp'. Pain sometimes related to movement, sometimes not. No radiation. Vital signs normal. ECG shows nonspecific ST-T changes. Troponin normal. Patient anxious, recently lost job. Doctor uncertain if cardiac or musculoskeletal vs anxiety.")
        ]
    }
    
    result = await graph.ainvoke(state)
    
    # Verify response exists
    assert "messages" in result
    assert len(result["messages"]) > 0
    
    # Verify Tier 2 assignment (NOT Tier 1 - patient is stable)
    response_content = result["messages"][-1].content.lower()
    assert "tier 2" in response_content
    assert "tier 1" not in response_content  # Should NOT be immediate


@pytest.mark.asyncio
async def test_edge_case_borderline_vital_signs_in_elderly_patient():
    """
    Test: Edge case - borderline vital signs in elderly patient
    """
    state = {
        "messages": [
            HumanMessage(content="Patient is an 82-year-old female with generalized weakness for 2 days. BP 95/60 (baseline 110/70), HR 92, temp 37.8°C. Mild confusion, oriented to person and place but not time. Labs show sodium 132, creatinine 1.4 (baseline 1.0). No obvious infection source. Patient lives alone, has been eating and drinking poorly. Doctor notes possible dehydration vs early sepsis vs medication effect.")
        ]
    }
    
    result = await graph.ainvoke(state)
    
    # Verify response exists
    assert "messages" in result
    assert len(result["messages"]) > 0
    
    # Verify Tier 1 assignment
    response_content = result["messages"][-1].content.lower()
    assert "tier 1" in response_content
    assert "immediate" in response_content


@pytest.mark.asyncio
async def test_error_scenario_missing_critical_test_results():
    """
    Test: Error scenario - missing critical test results
    """
    state = {
        "messages": [
            HumanMessage(content="Patient is a 55-year-old male with severe abdominal pain for 6 hours, constant, 8/10 intensity. Pain in epigastric region. Patient vomiting. Vital signs: BP 100/65, HR 105, temp 37.2°C. Abdomen rigid with guarding. Doctor suspects perforated viscus but imaging not yet available.")
        ]
    }
    
    result = await graph.ainvoke(state)
    
    # Verify response exists
    assert "messages" in result
    assert len(result["messages"]) > 0
    
    # Verify Tier 1 assignment despite missing data
    response_content = result["messages"][-1].content.lower()
    assert "tier 1" in response_content
    assert "immediate" in response_content


@pytest.mark.asyncio
async def test_error_scenario_vague_symptoms_without_objective_findings():
    """
    Test: Error scenario - vague symptoms without objective findings
    """
    state = {
        "messages": [
            HumanMessage(content="Patient reports 'not feeling well' for several weeks. Denies specific symptoms when asked. Says everything hurts but can't localize. No fever documented. Patient states 'doctors never help me.' No physical exam findings documented. No test results provided. Doctor notes patient seems frustrated.")
        ]
    }
    
    result = await graph.ainvoke(state)
    
    # Verify response exists
    assert "messages" in result
    assert len(result["messages"]) > 0
    
    # Verify agent acknowledges insufficient data
    response_content = result["messages"][-1].content.lower()
    assert "tier 3" in response_content or "insufficient" in response_content or "limited" in response_content